# -*- coding: utf-8 -*-
"""Customer segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hybDYTgr2CCGaGu8KUszPwDNgfxcY3Ag

#**CUSTOMER SEGMENTATION**

import librairies
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from sklearn.cluster import KMeans

"""import dataset"""

df =pd.read_csv("/content/drive/MyDrive/dataset/Mall_Customers.csv")

df.head()

df.tail()

df.shape

df.info()

df.describe()

"""#conclusions
* max age -70
*min - 18

- average income : 60K $
"""

plt.figure(figsize =(20,15))

sns.countplot(data = df,x ='Age' )

plt.title('Female vs Male')
df['Gender'].value_counts().plot(kind = 'pie',autopct='%1.1f%%', shadow =True )
plt.ylabel('')
plt.legend()

"""#conclusion
 - Number of females are more than males.
 - females 12% more than males.
 - females visit the mall most.
"""

df.head(2)

#Distribution of Income
plt.figure(figsize =(20,15))
sns.countplot(x='Annual Income (k$)', data=df,palette='Set2')
plt.title("Distribution of annual income")

""" - customers of 54K ,78K are mostly visiting mall`"""

#distribution of income based on gender

sns.histplot(df,x ='Annual Income (k$)',hue ='Gender',multiple = 'stack')

sns.lmplot(data =df,x = 'Spending Score (1-100)',y ="Age",hue ='Gender')

"""**Machine learning**"""

df.head()

from sklearn.preprocessing import LabelEncoder

lbl = LabelEncoder()

df['Gender'] = lbl.fit_transform(df['Gender'])

df.head()

df.drop('CustomerID',axis = 1, inplace =True)

df.head()

ssd = []

for i in range(1,11):
  kmodel = KMeans(n_clusters= i, n_init = 15, max_iter =500)
  kmodel.fit(df)
  ssd.append(kmodel.inertia_)

ssd #number of cluster increases the wcss dcreases

plt.plot(range(1,11), ssd,marker = 'o')
plt.grid()

"""#after 6 distance decreases"""

kmodel = KMeans(n_clusters = 6)

kmodel.fit(df)

clus = kmodel.predict(df)

clus

kmodel.cluster_centers_

len(kmodel.cluster_centers_)

df.head()

df['Cluster'] = clus

df.head()